### ISSUE TITLE
02-first-java Programs Not Matching With Kunal's Questions

### ISSUE THREAD

**Issue by Lyon03** [thatbeautifuldream/java-dsa-bootcamp#65]
For example,
The code given in the file 02-first-java for Q1.java is the code that gives the factorial of a number. Whereas in Kunal's assignment the corresponding question is to check whether a number is odd or eve which is done in Q2.java.

I found this to be the issue for multiple questions. I would love to be assigned to fix it.

**Comment by thatbeautifuldream** [comment]
I've been busy with a lot of other work related to college and haven't been able to make time fix these. There might have been assignment changes itself, earlier when the course started the assignments were different people have been contributing to Kunals repository as well that's why might be. Yes definitely you can just send a PR and I'll be more than happy to merge it.

**Comment by Lyon03** [comment]
Awesome! I'll try my best :)

**Comment by VishwaS-22** [comment]
Hey @Lyon03! Are you currently working on this Issue? If not @thatbeautifuldream please assign this Issue to me. I've codes that currently matches Kunal's DSA-Java Bootcamp. Can I create a PR for this?

Thank you!

**Comment by thatbeautifuldream** [comment]
You can make a PR for the same, thank you for yoyr contribution.

**Comment by VishwaS-22** [comment]
Hey @thatbeautifuldream! I made a PR for that, Please check it. Am very much happy to contribute. Hope this will help the folks.
If any changes required means please feel free to share, I'm very much happy to help.

Thank You!
